---
title: "Practicals"
output: 
html_document:
  toc: true
  toc_float: true
  collapsed: false
  number_sections: false
  toc_depth: 1
---

Last changes: `r Sys.Date()`

Here you can find the practicals of Communicatiewetenschapper in de maak (CWIDM). This is a pre-master course of the Vrije universiteit Amsterdam (VU). These practicals will discuss preperatory analyses using the package `tidyverse`, reliability analyses, linear regression models with moderation and mediation and AN(C)OVA with moderation. It is recommended to already download the packages on your computer before starting the practicals as it otherwise might take you some time during the completion of the practicals itself. The following packages are required for the practicals:

# Practical 1: Reliability analysis.

Last changes: `r Sys.Date()`

This week, you will learn how to conduct a lreliability analysis including a factoranalysis.

This week, we will need the following packages:

Video:

-   Link to video regression with mediation:

Dataset:

-   You can download the dataset for this week [here](files/CWIDM_practicum_2_dataset.csv?raw=true).

Assignment:

-   Assignment description:

    -   [View Assignment](files/CWIDM_practicum_2_opdracht%20(1)%20(1).pdf)

-   Assignment with answers

    -   [View Answers](files/CWIDM_practicum_2_antwoorden.pdf)

-   You can view the R-script [here](files/CWIDM_practicum_2_script%20(2).R).

-   You can view the assignment script and output (R-markdown) [here](Practicum_2_markdown.html).

# Practical 2: Regression, mediation.

Last changes: `r Sys.Date()`

This week, you will learn how to conduct a linear regression with mediation. We will use the `lm`-function for this as well as Hayes-Process.

This week, we will need the following packages:

Video:

-   Link to video regression with mediation:

Dataset:

-   You can download the dataset for this week [here](files/CWIDM_practicum_2_dataset.csv?raw=true).

Assignment:

-   Assignment description:

    -   [View Assignment](files/CWIDM_practicum_2_opdracht%20(1)%20(1).pdf)

-   Assignment with answers

    -   [View Answers](files/CWIDM_practicum_2_antwoorden.pdf)

-   You can view the R-script [here](files/CWIDM_practicum_2_script%20(2).R).

-   You can view the assignment script and output (R-markdown) [here](Practicum_2_markdown.html).

# Practical 3: Regression, moderation.

Last changes: `r Sys.Date()`

This week, you will learn how to conduct a linear regression with moderation.

This week, we will need the following packages:

Video:

-   Link to video regression with moderation:

Dataset:

-   You can download the dataset for this week [here](files/CWIDM_practicum_2_dataset.csv?raw=true).

Assignment:

-   Assignment description:

    -   [View Assignment](files/CWIDM_practicum_2_opdracht%20(1)%20(1).pdf)

-   Assignment with answers

    -   [View Answers](files/CWIDM_practicum_2_antwoorden.pdf)

-   You can view the R-script [here](files/CWIDM_practicum_2_script%20(2).R).

-   You can view the assignment script and output (R-markdown) [here](Practicum_2_markdown.html).

# Practical 5: AN(C)OVA.

Last changes: `r Sys.Date()`

This week, you will learn how to conduct an AN(C)OVA with moderation.

This week, we will need the following packages:

Video:

-   Link to video AN(C)OVA with moderation:

Dataset:

-   You can download the dataset for this week [here](files/CWIDM_practicum_2_dataset.csv?raw=true).

Assignment:

-   Assignment description:

    -   [View Assignment](files/CWIDM_practicum_2_opdracht%20(1)%20(1).pdf)

-   Assignment with answers

    -   [View Answers](files/CWIDM_practicum_2_antwoorden.pdf)

-   You can view the R-script [here](files/CWIDM_practicum_2_script%20(2).R).

-   You can view the assignment script and output (R-markdown) [here](Practicum_2_markdown.html).

# Practical 6: Data cleaning.

Last changes: `r Sys.Date()`

This week, you will learn how to process your dataset in such a way that you can start with the analyses as discussed in previous practicals.

This week, we will need the following packages:

Video:

-   Link to video datacleaning:

Dataset:

-   You can download the dataset for this week [here](files/CWIDM_practicum_2_dataset.csv?raw=true).

Assignment:

-   Assignment description:

    -   [View Assignment](files/CWIDM_practicum_2_opdracht%20(1)%20(1).pdf)

-   Assignment with answers

    -   [View Answers](files/CWIDM_practicum_2_antwoorden.pdf)

-   You can view the R-script [here](files/CWIDM_practicum_2_script%20(2).R).

-   You can view the assignment script and output (R-markdown) [here](Practicum_2_markdown.html).
